### ISSUE TITLE
2015.3.30 issue

### ISSUE THREAD

**Issue by zhanglei1949** [cpxdudu/homework#1]
1.如何解决输入字符导致的接收错误？
2.比较过程如何更为简洁？
3.建议用用数组~。
4.编写风格好评。

**Comment by ieee-wangwei** [comment]
1.代码结构比较易懂
2.可能比较的过程长了一些
3.生成随机数的方法有待提高

**Comment by ghost** [comment]
1.建议完善检查输入。
2.缩进合理，结构清晰。
3.比较过程（包括随机数比较部分）分情况有点繁杂，建议优化。
